### ISSUE TITLE
HTTP Url connection not closed

### ISSUE THREAD

**Issue by mathroule** [aritraroy/RxMagneto#9]
When strict mode is enabled, I get this stacktrace:
```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                         java.lang.Throwable: Explicit termination method 'close' not called
                                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                             at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
                                                                             at java.net.Socket.createImpl(Socket.java:470)
                                                                             at java.net.Socket.getImpl(Socket.java:536)
                                                                             at java.net.Socket.setSoTimeout(Socket.java:1127)
                                                                             at com.android.okhttp.Connection.connectSocket(Connection.java:195)
                                                                             at com.android.okhttp.Connection.connect(Connection.java:172)
                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
                                                                             at com.aritraroy.rxmagneto.RxMagnetoInternal.lambda$isPackageUrlValid$0(RxMagnetoInternal.java:73)
                                                                             at com.aritraroy.rxmagneto.RxMagnetoInternal$$Lambda$1.subscribe(Unknown Source)
                                                                             at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                             at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                             at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
                                                                             at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                                             at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                             at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                             at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                             at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:761)
```

I think it's due, to `httpURLConnection.getResponseCode()` which does not properly close input stream, see: https://stackoverflow.com/questions/15789789/android-strictmode-throwable-explicit-termination-method-end-not-called
Also HttpURLConnection is never disconnected. Replacing usage of HttpURLConnection by Jsoup fix the probleme. PR is comming.

**Comment by mathroule** [comment]
See PR https://github.com/aritraroy/RxMagneto/pull/10

**Comment by aritraroy** [comment]
Inspired by PR #10 and fixed in the current major re-write.

**Comment by mathroule** [comment]
HttpURLConnection is also used in release 2.0.0, so the strict mode error is still here :(
Why not replacing HttpURLConnection  with Jsoup like proposed in my PR?
